### ISSUE TITLE
支持忽略assets文件夹下的2.0x和3.0x文件夹

### ISSUE THREAD

**Issue by xiangzy1** [fluttercandies/assets_generator#1]
目前一张图片会生成三个变量(1x 2x 3x)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/assets_generator/commit/c2d204e436207455e587b0ccf174d493b7bd4538

**Comment by zmtzawqlp** [comment]
done

**Comment by xiangzy1** [comment]
pubspec.yaml中assets下还是会自动生成2.0x、3.0x、而且貌似缩进有些问题？

**Comment by zmtzawqlp** [comment]
pubspec.yaml 里面不添加是不行的吧？？？ 你看看文档呢？？不增加。打包的时候不会打包进去啊https://flutter.dev/docs/development/ui/assets-and-images

**Comment by zmtzawqlp** [comment]
Each entry in the asset section of the pubspec.yaml should correspond to a real file, with the exception of the main asset entry. If the main asset entry doesn’t correspond to a real file, then the asset with the lowest resolution is used as the fallback for devices with device pixel ratios below that resolution. The entry should still be included in the pubspec.yaml manifest, however.

**Comment by xiangzy1** [comment]
我居然不知道 一直没写过...

**Comment by zmtzawqlp** [comment]
> 我居然不知道 一直没写过...
哈哈哈。。你之前一直都只用的1.0的图片。没有声明

**Comment by xiangzy1** [comment]
这块感觉文档说的不是很清楚，看起来是1.0x 2.0x是一种特殊的目录结构，声明了1x的资源之后，需要更高倍数的它会自动在2.0x 3.0x去找。我用了挺久flutter一直这么写也没发现图片会糊，所以感觉还是不太确定这个问题。搜了一下，也有说只用声明1.0x就可以的。

**Comment by zmtzawqlp** [comment]
很简单。你2.0里面换个不一样的图片就能试出来了。或者你试试打包。不定义。能打包进去吗？

**Comment by zmtzawqlp** [comment]
看起来真的不需要定义。。这个有点尴尬呢

**Comment by zmtzawqlp** [comment]
我又完善了一些。把倍图的各种情况结合文档和实际都考虑了下。空了你试试呢。还有其他问题没有

**Comment by xiangzy1** [comment]
应该是没问题了
