### ISSUE TITLE
在pubspec.yaml中生成assets的时候能否忽略ttf文件和只包含ttf文件的文件夹

### ISSUE THREAD

**Issue by Zhangxxl** [fluttercandies/assets_generator#2]
如题, ttf格式的字体文件不需要配置到assets节点下, 只需要配置在fonts节点下就行了

**Comment by zmtzawqlp** [comment]
试试 --const-ignore    The regular to ignore some consts

**Comment by zmtzawqlp** [comment]
还没有单独为font独立做。
