### ISSUE TITLE
安装执行后错误如下

### ISSUE THREAD

**Issue by bhk545145** [fluttercandies/assets_generator#6]
agen -t d -s -r lwu

Unhandled exception:
type 'Null' is not a subtype of type 'String' in type cast
#0      new Argument (package:assets_generator/src/arg/arg.dart:10:58)
#1      new ConstIgnore (package:assets_generator/src/arg/const_ignore.dart)
#2      main (file:///Users/baihongkun/.pub-cache/hosted/pub.dartlang.org/assets_generator-3.0.0/bin/assets_generator.dart:31:35)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by NoFearInMyHeart** [comment]
我也碰见了一样的问题

**Comment by zmtzawqlp** [comment]
已修复。请稍后重新安装

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/assets_generator/commit/35caacdf5a6de289d44e3db3630abf1f1598590c
